version: '3'

services:
  openweathermap:
    container_name: data-producer
    image: data-producer
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: weather
      SLEEP_TIME: 60

networks:
  default:
    external:
      name: kafka-network
