version: '3'

services:
  cassandradb:
    container_name: data-warehouse
    # image: bootstrapcassandra
    image: data-warehouse
    build: .
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - $PWD/warehouse/data:/var/lib/cassandra
networks:
  default:
    external:
      name: cassandra-network
