version: '3'

services:
  faker:
    container_name: producer-faker
    image: producer-faker
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: faker
      SLEEP_TIME: 60

networks:
  default:
    external:
      name: kafka-network
