version: '3'

services:
  weatherconsumer:
    container_name: consumer-logging
    image: consumer-logging
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: weather
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
    command: ["python", "-u","python/logging_consumer.py"]

networks:
  default:
    external:
      name: kafka-network
