version: "3"

services:
  datavis:
    container_name: data-vis
    hostname: data-vis
    image: data-vis
    build: .
    environment:
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
      WEATHER_TABLE: weatherreport
      TWITTER_TABLE: twitterdata
    ports:
        - 8888:8888
    volumes:
      - $PWD/data-vis/python:/usr/app
networks:
  default:
    external:
      name: cassandra-network
